### PR TITLE
ledc.h - fix extern "C" to include ledc_cb_register() (IDFGH-6484)

### PR DESCRIPTION
**Pull request by vortigont**
ledc_cb_register() function is out of scope of "#ifdef __cplusplus", introduced in 9d098cc

this patch fixes linker error "undefined reference to `ledc_cb_register()" if build with cpp

### CODE REVIEW

**Comment by Alvin1Zhang** [comment]
Thanks for your contribution.

**Review by mahavirj — APPROVED** [review]

**Comment by mahavirj** [comment]
sha=d4de08182eab8fc3415f20265181bf141eef7376
