### ISSUE TITLE
CMake error after updating from v4.3.1 or v4.3.2 to v4.4 or v4.4.1 (IDFGH-7309)

### ISSUE THREAD

**Issue by vdm97** [espressif/esp-idf#8898]
## Environment

- Development Kit: none
- Module or chip used: ESP32-WROOM-32
- IDF version: v4.3.1, v4.3.2, v4.4, v4.4.1
- Build System: CMake
- Compiler version: Standard version of each release
- Operating System: Windows
- (Windows only) environment type: PowerShell
- Using an IDE?: VS Code with Espressif IDF v1.4.0
- Power Supply: Implemented in custom board

## Problem Description

When updating from v4.3.1 or v4.3.2 to v4.4 or v4.4.1 i get an compilation error. Somehow `CONFIG_BOOTLOADER_OFFSET_IN_FLASH` does not get set to the real value, when the file `build/bootloader/build.ninja` gets generated. Therefore the file contains the following:

```
#############################################
# Custom command for esp-idf\esptool_py\CMakeFiles\bootloader_check_size

build esp-idf/esptool_py/CMakeFiles/bootloader_check_size: CUSTOM_COMMAND || _project_elf_src bootloader.elf esp-idf/bootloader_support/libbootloader_support.a esp-idf/efuse/libefuse.a esp-idf/esp_common/libesp_common.a esp-idf/esp_hw_support/libesp_hw_support.a esp-idf/esp_rom/libesp_rom.a esp-idf/esp_system/libesp_system.a esp-idf/hal/libhal.a esp-idf/log/liblog.a esp-idf/main/libmain.a esp-idf/micro-ecc/libmicro-ecc.a esp-idf/soc/libsoc.a esp-idf/spi_flash/libspi_flash.a esp-idf/xtensa/libxtensa.a gen_project_binary
  COMMAND = cmd.exe /C "cd /D C:\path\build\bootloader\esp-idf\esptool_py && c:\Users\user\esp\esp-idf-tools\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Users/user/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader CONFIG_BOOTLOADER_OFFSET_IN_FLASH C:/path/build/bootloader/bootloader.bin"

# =============================================================================
# Write statements declared in CMakeLists.txt:
# C:/Users/user/esp/esp-idf/CMakeLists.txt
# =============================================================================
#############################################
```

If i manually change `CONFIG_BOOTLOADER_OFFSET_IN_FLASH` to `0x1000` the compilation succeeds. I still get [this](https://github.com/espressif/esp-idf/issues/8897) error. But that error is probably unrelated so i created a seperate issue.

If more specific information is needed, i will gladly provide it.

## Debug Logs

```
> Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .. <

-- Found Git: C:/Users/user/esp/esp-idf-tools/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1")
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file C:/path/sdkconfig_debug
Loading defaults file C:/path/sdkconfig_debug...
-- Found PythonInterp: C:/Users/user/esp/esp-idf-tools/python_env/idf4.4_py3.8_env/Scripts/python.exe (found version "3.8.7")
-- Could NOT find Perl (missing: PERL_EXECUTABLE) 
-- App "esp-app" version: 100
-- Adding linker script C:/path/build/esp-idf/esp_system/app/memory.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_system/app/esp32/sections.app.in
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.api.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.libgcc.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.newlib-data.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.syscalls.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.newlib-funcs.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.newlib-time.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/soc/esp32/app/esp32.peripherals.app
-- Components: app_trace app_update asio bootloader bootloader_support bt cbor cmock coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_eth 
esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_lcd esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test ieee802154 jsmn json libsodium log lwip main mbedtls mdns mqtt newlib 
nghttp nvs_flash openssl openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: C:/Users/user/esp/esp-idf/components/app_trace C:/Users/user/esp/esp-idf/components/app_update C:/Users/user/esp/esp-idf/components/asio C:/path/components/bootloader C:/Users/user/esp/esp-idf/components/bootloader_support C:/Users/user/esp/esp-idf/components/bt C:/Users/user/esp/esp-idf/components/cbor C:/Users/user/esp/esp-idf/components/cmock C:/Users/user/esp/esp-idf/components/coap C:/Users/user/esp/esp-idf/components/console C:/Users/user/esp/esp-idf/components/cxx C:/Users/user/esp/esp-idf/components/driver C:/Users/user/esp/esp-idf/components/efuse C:/Users/user/esp/esp-idf/components/esp-tls C:/Users/user/esp/esp-idf/components/esp32 C:/Users/user/esp/esp-idf/components/esp_adc_cal C:/Users/user/esp/esp-idf/components/esp_common C:/Users/user/esp/esp-idf/components/esp_eth C:/Users/user/esp/esp-idf/components/esp_event C:/Users/user/esp/esp-idf/components/esp_gdbstub C:/Users/user/esp/esp-idf/components/esp_hid C:/Users/user/esp/esp-idf/components/esp_http_client C:/Users/user/esp/esp-idf/components/esp_http_server C:/Users/user/esp/esp-idf/components/esp_https_ota C:/Users/user/esp/esp-idf/components/esp_https_server C:/Users/user/esp/esp-idf/components/esp_hw_support C:/Users/user/esp/esp-idf/components/esp_ipc C:/Users/user/esp/esp-idf/components/esp_lcd C:/Users/user/esp/esp-idf/components/esp_local_ctrl C:/Users/user/esp/esp-idf/components/esp_netif C:/Users/user/esp/esp-idf/components/esp_phy C:/Users/user/esp/esp-idf/components/esp_pm C:/Users/user/esp/esp-idf/components/esp_ringbuf C:/Users/user/esp/esp-idf/components/esp_rom C:/Users/user/esp/esp-idf/components/esp_serial_slave_link C:/Users/user/esp/esp-idf/components/esp_system C:/Users/user/esp/esp-idf/components/esp_timer C:/Users/user/esp/esp-idf/components/esp_websocket_client C:/Users/user/esp/esp-idf/components/esp_wifi C:/Users/user/esp/esp-idf/components/espcoredump C:/Users/user/esp/esp-idf/components/esptool_py C:/Users/user/esp/esp-idf/components/expat C:/Users/user/esp/esp-idf/components/fatfs C:/Users/user/esp/esp-idf/components/freemodbus C:/Users/user/esp/esp-idf/components/freertos C:/Users/user/esp/esp-idf/components/hal C:/Users/user/esp/esp-idf/components/heap C:/Users/user/esp/esp-idf/components/idf_test C:/Users/user/esp/esp-idf/components/ieee802154 C:/Users/user/esp/esp-idf/components/jsmn C:/Users/user/esp/esp-idf/components/json C:/Users/user/esp/esp-idf/components/libsodium C:/Users/user/esp/esp-idf/components/log C:/Users/user/esp/esp-idf/components/lwip C:/path/main C:/Users/user/esp/esp-idf/components/mbedtls C:/Users/user/esp/esp-idf/components/mdns C:/Users/user/esp/esp-idf/components/mqtt C:/Users/user/esp/esp-idf/components/newlib C:/Users/user/esp/esp-idf/components/nghttp C:/Users/user/esp/esp-idf/components/nvs_flash C:/Users/user/esp/esp-idf/components/openssl C:/Users/user/esp/esp-idf/components/openthread C:/Users/user/esp/esp-idf/components/partition_table C:/Users/user/esp/esp-idf/components/perfmon C:/Users/user/esp/esp-idf/components/protobuf-c C:/Users/user/esp/esp-idf/components/protocomm C:/Users/user/esp/esp-idf/components/pthread C:/Users/user/esp/esp-idf/components/sdmmc C:/Users/user/esp/esp-idf/components/soc C:/Users/user/esp/esp-idf/components/spi_flash C:/Users/user/esp/esp-idf/components/spiffs C:/Users/user/esp/esp-idf/components/tcp_transport C:/Users/user/esp/esp-idf/components/tcpip_adapter C:/Users/user/esp/esp-idf/components/tinyusb C:/Users/user/esp/esp-idf/components/ulp C:/Users/user/esp/esp-idf/components/unity C:/Users/user/esp/esp-idf/components/usb C:/Users/user/esp/esp-idf/components/vfs C:/Users/user/esp/esp-idf/components/wear_levelling C:/Users/user/esp/esp-idf/components/wifi_provisioning C:/Users/user/esp/esp-idf/components/wpa_supplicant C:/Users/user/esp/esp-idf/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/path/build

> Executing task: ninja  <

[14/1020] Generating ../../partition_table/partition-table.bin
Partition table binary generated. Contents:
******************************************************************************* 
# ESP-IDF Partition Table
# Name, Type, SubType, Offset, Size, Flags
factory,app,factory,0x10000,1M,
www,data,spiffs,0x110000,4M,
crc,240,0,0x510000,4K,
******************************************************************************* 
[459/1020] Performing configure step for 'bootloader'
-- Found Git: C:/Users/user/esp/esp-idf-tools/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1")
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/user/esp/esp-idf-tools/tools/xtensa-esp32-elf/esp-2021r2-patch2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file C:/path/sdkconfig_debug
warning: the hex symbol ESP_MAIN_TASK_AFFINITY (defined at C:/Users/user/esp/esp-idf/components/esp_system/Kconfig:191) has a non-hex default FREERTOS_NO_AFFINITY (undefined)
-- Adding linker script C:/Users/user/esp/esp-idf/components/soc/esp32/app/esp32.peripherals.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.api.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.libgcc.app
-- Adding linker script C:/Users/user/esp/esp-idf/components/esp_rom/esp32/app/esp32.rom.newlib-funcs.app
-- Adding linker script C:/path/components/bootloader/subproject/main/app/esp32/bootloader.app
-- Adding linker script C:/path/components/bootloader/subproject/main/app/esp32/bootloader.rom.app
-- Components: bootloader bootloader_support efuse esp32 esp_common esp_hw_support esp_rom esp_system esptool_py hal log main micro-ecc newlib partition_table soc spi_flash xtensa
-- Component paths: C:/path/components/bootloader C:/Users/user/esp/esp-idf/components/bootloader_support C:/Users/user/esp/esp-idf/components/efuse C:/Users/user/esp/esp-idf/components/esp32 C:/Users/user/esp/esp-idf/components/esp_common C:/Users/user/esp/esp-idf/components/esp_hw_support C:/Users/user/esp/esp-idf/components/esp_rom C:/Users/user/esp/esp-idf/components/esp_system C:/Users/user/esp/esp-idf/components/esptool_py C:/Users/user/esp/esp-idf/components/hal C:/Users/user/esp/esp-idf/components/log C:/path/components/bootloader/subproject/main C:/path/components/bootloader/subproject/components/micro-ecc C:/Users/user/esp/esp-idf/components/newlib C:/Users/user/esp/esp-idf/components/partition_table C:/Users/user/esp/esp-idf/components/soc C:/Users/user/esp/esp-idf/components/spi_flash C:/Users/user/esp/esp-idf/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/path/build/bootloader 
[608/1020] Performing build step for 'bootloader'
FAILED: bootloader-prefix/src/bootloader-stamp/bootloader-build bootloader/bootloader.elf bootloader/bootloader.bin bootloader/bootloader.map
cmd.exe /C "cd /D C:\path\build\bootloader && C:\Users\user\esp\esp-idf-tools\tools\cmake\3.20.3\bin\cmake.exe --build ."
[1/97] Generating project_elf_src_esp32.c
[2/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/soc_include_legacy_warn.c.obj
[3/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/lldesc.c.obj      
[4/97] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/mpu_hal.c.obj     
[5/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/adc_periph.c.obj
[6/97] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/cpu_hal.c.obj     
[7/97] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/wdt_hal_iram.c.obj[8/97] Building C object CMakeFiles/bootloader.elf.dir/project_elf_src_esp32.c.obj
[9/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/interrupts.c.obj
[10/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/i2s_periph.c.obj
[11/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/lcd_periph.c.obj
[12/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/gpio_periph.c.obj
[13/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/ledc_periph.c.obj
[14/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/dac_periph.c.obj
[15/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/pcnt_periph.c.obj
[16/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/mcpwm_periph.c.obj
[17/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/rtc_io_periph.c.obj
[18/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/rmt_periph.c.obj
[19/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/i2c_periph.c.obj
[20/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/touch_sensor_periph.c.obj
[21/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/sdio_slave_periph.c.obj
[22/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/sdmmc_periph.c.obj
[23/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/uart_periph.c.obj
[24/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/sigmadelta_periph.c.obj
[25/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/spi_periph.c.obj
[26/97] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32/timer_periph.c.obj
[27/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_mem.c.obj
[28/97] Building C object esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32/spi_flash_rom_patch.c.obj
[29/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_random.c.obj
[30/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_common.c.obj
[31/97] Building C object esp-idf/micro-ecc/CMakeFiles/__idf_micro-ecc.dir/uECC_verify_antifault.c.obj
[32/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_flash.c.obj
[33/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_clock_init.c.obj
[34/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_common_loader.c.obj
[35/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_encrypt.c.obj
[36/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/secure_boot.c.obj
[37/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_random_esp32.c.obj
[38/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_qio_mode.c.obj
[39/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_utility.c.obj
[40/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp_image_format.c.obj
[41/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_partitions.c.obj
[42/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_console_loader.c.obj
[43/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32/bootloader_soc.c.obj
[44/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_flash_config_esp32.c.obj
[45/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_init.c.obj
[46/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_efuse_esp32.c.obj
[47/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_clock_loader.c.obj
[48/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_console.c.obj
[49/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_panic.c.obj
[50/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32/bootloader_sha.c.obj
[51/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32/esp_efuse_utility.c.obj
[52/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32/esp_efuse_table.c.obj
[53/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32/esp_efuse_fields.c.obj
[54/97] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/esp_err.c.obj
[55/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_api_key_esp32.c.obj
[56/97] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32/bootloader_esp32.c.obj
[57/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_fields.c.obj
[58/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_utility.c.obj
[59/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/compare_set.c.obj
[60/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_pm.c.obj
[61/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_clk_init.c.obj
[62/97] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_api.c.obj
[63/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_time.c.obj
[64/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_init.c.obj
[65/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_clk.c.obj
[66/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/cpu_util.c.obj
[67/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_sleep.c.obj
[68/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/rtc_wdt.c.obj
[69/97] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_sys.c.obj
[70/97] Building C object esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/eri.c.obj  
[71/97] Building C object esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/xt_trax.c.obj
[72/97] Building ASM object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_longjmp.S.obj
[73/97] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_uart.c.obj
[74/97] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_crc.c.obj
[75/97] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32/chip_info.c.obj
[76/97] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_tjpgd.c.obj
[77/97] Building C object esp-idf/esp_common/CMakeFiles/__idf_esp_common.dir/src/esp_err_to_name.c.obj
[78/97] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log_noos.c.obj   
[79/97] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log_buffers.c.obj[80/97] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/bootloader_start.c.obj
[81/97] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log.c.obj        
[82/97] Linking C static library esp-idf\log\liblog.a
[83/97] Linking C static library esp-idf\esp_rom\libesp_rom.a
[84/97] Linking C static library esp-idf\esp_common\libesp_common.a
[85/97] Linking C static library esp-idf\xtensa\libxtensa.a
[86/97] Linking C static library esp-idf\esp_hw_support\libesp_hw_support.a     
[87/97] Linking C static library esp-idf\esp_system\libesp_system.a
[88/97] Linking C static library esp-idf\efuse\libefuse.a
[89/97] Linking C static library esp-idf\bootloader_support\libbootloader_support.a
[90/97] Linking C static library esp-idf\spi_flash\libspi_flash.a
[91/97] Linking C static library esp-idf\micro-ecc\libmicro-ecc.a
[92/97] Linking C static library esp-idf\soc\libsoc.a
[93/97] Linking C static library esp-idf\hal\libhal.a
[94/97] Linking C static library esp-idf\main\libmain.a
[95/97] Linking C executable bootloader.elf
[96/97] Generating binary image from built executable
esptool.py v3.2-dev
Merged 1 ELF section
Generated C:/path/build/bootloader/bootloader.bin
[97/97] cmd.exe /C "cd /D C:\path\build\bootloader\esp-idf\esptool_py && c:\Users\user\esp\esp-idf-tools\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Users/user/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader CONFIG_BOOTLOADER_OFFSET_IN_FLASH C:/path/build/bootloader/bootloader.bin"
FAILED: esp-idf/esptool_py/CMakeFiles/bootloader_check_size
cmd.exe /C "cd /D C:\path\build\bootloader\esp-idf\esptool_py 
&& c:\Users\user\esp\esp-idf-tools\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Users/user/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader CONFIG_BOOTLOADER_OFFSET_IN_FLASH C:/path/build/bootloader/bootloader.bin"
Traceback (most recent call last):
  File "C:/Users/user/esp/esp-idf/components/partition_table/check_sizes.py", line 148, in <module>
    main()
  File "C:/Users/user/esp/esp-idf/components/partition_table/check_sizes.py", line 142, in main
    check_bootloader(args.offset, int(args.bootloader_offset, 0), args.bootloader_binary)
ValueError: invalid literal for int() with base 0: 'CONFIG_BOOTLOADER_OFFSET_IN_FLASH'
ninja: build stopped: subcommand failed.
[609/1020] Linking C static library esp-idf\nghttp\libnghttp.a
ninja: build stopped: subcommand failed.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1.
```

**Comment by igrr** [comment]
@vdm97 does this issue happen if you build one of IDF example projects? In your project, does `idf.py fullclean` help with this issue?

**Comment by igrr** [comment]
I think I understand now, it looks like your project is using a customized bootloader? If you have a custom bootloader derived from IDF 4.3.x, it will not be built correctly with IDF 4.4.x. Could you please try to run your application with the standard bootloader provided in IDF first, to see if that is the issue?
(I think it is also the reason for the other issue you have reported.)

**Comment by vdm97** [comment]
@igrr Thank you for your fast response. Your finding of the custom bootloader is correct. Using `idf.py fullclean` does not help.
I am now trying to replace the custom bootloader with the standard one. Did the custom bootloader configuration change completely from v4.3 to v4.4? I cannot find [custom bootloader examples for version v4.3.2](https://github.com/espressif/esp-idf/tree/v4.3.2/examples) but there is an [example for version v4.4.1](https://github.com/espressif/esp-idf/tree/v4.4.1/examples/custom_bootloader). I inherited the project so i do not fully understand the layout but there is a `components\bootloader\` subdirectory in the project. Should i move the relevant contents to the new `bootloader_components\main\` _format_? And what would be easier: Creating a new project and moving all content or keeping the project but replacing `components\bootloader\` with `bootloader_components\main\`?

**Comment by igrr** [comment]
I think the easiest way to move you bootloader customizations is as follows:

1. Compare (using some diff tool) your project's `components\bootloader` subdirectory with `%IDF_PATH%\components\bootloader`. Find the bootloader customizations which were done in your project.
2. If the customizations are small and can be done using [bootloader hooks](https://github.com/espressif/esp-idf/tree/master/examples/custom_bootloader/bootloader_hooks), this is the best option. It is much more likely that such customizations will be portable to newer versions of ESP-IDF. In this case, remove `components\bootloader`and add `bootloader_components\my_boot_hooks` as shown in that example, then port over your custom functionality.
3. If the customizations are more significant, try to do them by [overriding the `main` component of the bootloader](https://github.com/espressif/esp-idf/tree/master/examples/custom_bootloader/bootloader_override). In this case, remove `components\bootloader` and add `bootloader_components\main`, as shown in the example,  then port your custom functionality.

Both of these options are more future-proof than overriding the complete bootloader.

**Comment by vdm97** [comment]
Thank you very much for your time! Option 2 worked very nice for me.
