### ISSUE TITLE
undefined reference to `app_main' when building project  (IDFGH-1318)

### ISSUE THREAD

**Issue by tutuwin** [espressif/esp-idf#3608]
----------------------------- Delete below -----------------------------

/home/linux/esp32/esp-idf/examples/get-started/ESP32_RC522/build/esp32/libesp32.a(cpu_start.o):(.literal.main_task+0x18): undefined reference to `app_main'
/home/linux/esp32/esp-idf/examples/get-started/ESP32_RC522/build/esp32/libesp32.a(cpu_start.o): In function `main_task':
/home/linux/esp32/esp-idf/components/esp32/cpu_start.c:515: undefined reference to `app_main'

**Comment by chegewara** [comment]
Do you have `void app_main()` function in any file in your project?
What is yours folders tree looks like?

**Comment by koobest** [comment]
If you are using Cmake to build your project, make sure your c source filename is included in `CMakeLists.txt` under the main folder.

```
set(COMPONENT_SRCS "hello_world_main.c"
                                              "file1.c"
                                              "file2..c")
```

**Comment by f00bard** [comment]
According to [the docs](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system-cmake.html#example-project) a CMakeLists.txt file isn't needed under the <project>/main folder.  However I'm running into the same issue (having used GNU Make until now).

**Comment by renzbagaporo** [comment]
Hi @f00bard , that part of the docs is outdated, will fix. `main` should be treated like any other component, with its own CMakeLists.txt.

**Comment by renzbagaporo** [comment]
@tutuwin Closing as there are no updates to the last question by @koobest.

**Comment by Arag0to** [comment]
Hi @renzbagaporo ,
I am running in the same kind of problem.
![Eclipse_bug_#2](https://user-images.githubusercontent.com/29052191/73949614-a3fac080-48c8-11ea-9505-6ffd78d05600.png)

This problem is happening to me because I'm trying to work in c++ with Esp-IDF V4.0 so I renamed the main.c with main.cpp and did the same in the CMakeList.txt.

It work for some time but then the library becomes "unresolved including" and this errors comes with it some time.
I don't totally understand this erros and would like to know of a fix that is good for more then a day.

Thanks

**Comment by chegewara** [comment]
Did you add:
`extern "C" void app_main()`

**Comment by Arag0to** [comment]
I tried it last week and it did'nt work but this time it did.
But new problem,
### main.cpp
![esp-idf bug #3](https://user-images.githubusercontent.com/29052191/73998670-62056500-4930-11ea-9dd8-c98469681c21.png)
It's a C main so can't use any C++ stuff.
It's a more basic problem but could someone help me. I found so little information on this and when I did I'm not sure if it's still good or expired since I'm on ESP-IDF V4.0

Also, I don't have the compiler error but since it still compile my code in C, it does'nt recognize the include in the class.
### spi.h
![esp-idf bug#4](https://user-images.githubusercontent.com/29052191/73998924-11dad280-4931-11ea-85ec-da2e4aafa3b4.png)
### spi.cpp
![esp-idf bug#5](https://user-images.githubusercontent.com/29052191/73998927-13a49600-4931-11ea-92b4-9bbfc285b902.png)

**Comment by renzbagaporo** [comment]
Have you added `spi.cpp` to the list of source files @Arag0to?

**Comment by su-Koch** [comment]
> 
> 
> I tried it last week and it did'nt work but this time it did.
> But new problem,
> ### main.cpp
> 
> ![esp-idf bug #3](https://user-images.githubusercontent.com/29052191/73998670-62056500-4930-11ea-9dd8-c98469681c21.png)
> It's a C main so can't use any C++ stuff.
> It's a more basic problem but could someone help me. I found so little information on this and when I did I'm not sure if it's still good or expired since I'm on ESP-IDF V4.0
> 
> Also, I don't have the compiler error but since it still compile my code in C, it does'nt recognize the include in the class.
> ### spi.h
> 
> ![esp-idf bug#4](https://user-images.githubusercontent.com/29052191/73998924-11dad280-4931-11ea-85ec-da2e4aafa3b4.png)
> ### spi.cpp
> 
> ![esp-idf bug#5](https://user-images.githubusercontent.com/29052191/73998927-13a49600-4931-11ea-92b4-9bbfc285b902.png)

I have exactly the same issue. I'trying to add an external class (cpp + h). As I'm a beginner in cmake (coming from Visual Studio), can anyone tell me how to include source and header files correctly to project? Thanks a lot.

**Comment by A-Babin** [comment]
Haven't seen this documented anywhere, but I've found that if you're defining your `app_main` in C++, the file containing it must not be named `main.cpp`, even if you do everything else right.

**Comment by A-Babin** [comment]
> > Haven't seen this documented anywhere, but I've found that if you're defining your `app_main` in C++, the file containing it must not be named `main.cpp`, even if you do everything else right.
> 
> Almost true. It has to be: `extern "C" app_main()` and can be in `main.cpp`

If that's what's intended, then there's a bug. IDF v4.3.1, Windows 10, just installed yesterday, I have a fresh copy of `hello_world.` Enabled C++ and added `extern "C"` and all that... ninja fails with `undefined reference to `app_main'`. I do nothing except rename `main.cpp` and update the main component CMakeLists, and it builds fine.

**Comment by chegewara** [comment]
please try `idf.py fullclean`

**Comment by A-Babin** [comment]
> please try `idf.py fullclean`

No affect.

**Comment by picli3** [comment]
> tengo el mismo problema en ubuntu20.04, idf v4.4, pero en windows funciona :(

yo lo resolvi usando el comando de crear proyectos
`idf.py create-project  NOMBRE_PROYECTO `
de esta forma te crea la estructura base, compilas y listo!

**Comment by TogetDair-OCS** [comment]
d\d\
