### ISSUE TITLE
CONFIG_STDATOMIC_S32C1I_SPIRAM_WORKAROUND missing implementation for __atomic_test_and_set, breaks stdatomic (IDFGH-14597)

### ISSUE THREAD

**Issue by nebkat** [espressif/esp-idf#15353]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.4

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

`std::atomic_flag` / `stdatomic.h` should work with `CONFIG_SPIRAM=y`.

### What is the actual behavior?

Linker error: `undefined reference to '__atomic_test_and_set'`.

### Steps to reproduce.

1. Clone https://github.com/nebkat/esp-idf-stdatomic-bug
2. `idf.py @profile/spiram build`

### Build or installation Logs.

```plain
FAILED: hello_world.elf
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\Espressif\tools\xtensa-esp-elf\esp-14.2.0_20241119\xtensa-esp-elf\bin\xtensa-esp32s3-elf-g++.exe -mlongcalls  -fno-builtin-memcpy -fno-builtin-memset -fno-builtin-bzero -fno-builtin-stpcpy -fno-builtin-strncpy -Wl,--cref -Wl,--defsym=IDF_TARGET_ESP32S3=0 -Wl,--Map=C:/Espressif/frameworks/esp-idf-v5.4/examples/get-started/hello_world/build/spiram/hello_world.map -Wl,--no-warn-rwx-segments -Wl,--orphan-handling=warn -fno-rtti -fno-lto -Wl,--gc-sections -Wl,--warn-common -T esp32s3.peripherals.ld -T esp32s3.rom.ld -T esp32s3.rom.api.ld -T esp32s3.rom.bt_funcs.ld -T esp32s3.rom.libgcc.ld -T esp32s3.rom.wdt.ld -T esp32s3.rom.version.ld -T esp32s3.rom.newlib.ld -T memory.ld -T sections.ld @CMakeFiles\hello_world.elf.rsp -o hello_world.elf && cd ."
C:/Espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: esp-idf/main/libmain.a(hello_world_main.c.obj):(.literal.app_main+0x0): undefined reference to `__atomic_test_and_set'
C:/Espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: esp-idf/main/libmain.a(hello_world_main.c.obj): in function `app_main':
C:/Espressif/frameworks/esp-idf-v5.4/examples/get-started/hello_world/main/hello_world_main.c:12:(.text.app_main+0xc): undefined reference to `__atomic_test_and_set'
collect2.exe: error: ld returned 1 exit status
```

### More Information.

See also:
* #4635

Appears to be introduced by 4f09fba1276306c221d6f9f7ce0983ee4d5f6e2a, no linker error when reverted.

**Comment by Lapshin** [comment]
@nebkat , thank you for the report. The issue https://github.com/espressif/esp-idf/issues/15167 has already been fixed in the master branch and backport is on its way to v5.4.
You may cherry-pick the commit 793e394f5a06a6ca945adc40cbe4d5485bccbc26 until the backport is not in place.
