### ISSUE TITLE
`struct wpa_auth_config` has no member named `sae_require_mfp` (IDFGH-14420)

### ISSUE THREAD

**Issue by AtkinEngineering** [espressif/esp-idf#15200]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.5-dev-1346-gcc9fb5bd5e

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Previous dev build compiled the code.

### What is the actual behavior?

Build now reports:
`/home/dev/esp/master/esp-idf/components/wpa_supplicant/esp_supplicant/src/esp_hostap.c:` In function 'hostap_init`:
`/home/dev/esp/master/esp-idf/components/wpa_supplicant/esp_supplicant/src/esp_hostap.c:` 171:14: error: `struct wpa_auth_config` has no member named `sae_require_mfp`
  171 |     auth_conf->sae_require_mfp = 1;

### Steps to reproduce.

Build using Espressif VS Code extension v1.90

### Build or installation Logs.

```plain
`/home/dev/esp/master/esp-idf/components/wpa_supplicant/esp_supplicant/src/esp_hostap.c:` In function 'hostap_init`:
`/home/dev/esp/master/esp-idf/components/wpa_supplicant/esp_supplicant/src/esp_hostap.c:` 171:14: error: `struct wpa_auth_config` has no member named `sae_require_mfp`
  171 |     auth_conf->sae_require_mfp = 1;
```
