### ISSUE TITLE
export.sh issue (IDFGH-2284)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#4425]
Today, after upgrading Ubuntu from 16.04 to 18.04, i encountered error i cant handle. 
I know its not esp-idf issue, because i found that many people got it after upgrading ubuntu. 
Error log looks like that:
```
Adding ESP-IDF tools to PATH...
Checking if Python packages are up to date...
Traceback (most recent call last):
  File "/home/chegewara/esp/esp-idf/tools/check_python_dependencies.py", line 17, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 86, in <module>
    import copy as _copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```
After few trials i found the solution is to install venv:
`sudo apt-get install python3-venv`

**Comment by chegewara** [comment]
After running `instll.sh` i get this:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chegewara/.espressif/python_env/idf4.1_py2.7_env/lib/python2.7/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/home/chegewara/.espressif/python_env/idf4.1_py2.7_env/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Traceback (most recent call last):
  File "/home/chegewara/esp/esp-idf/tools/idf_tools.py", line 1349, in <module>
    main(sys.argv[1:])
  File "/home/chegewara/esp/esp-idf/tools/idf_tools.py", line 1345, in main
    action_func(args)
  File "/home/chegewara/esp/esp-idf/tools/idf_tools.py", line 1163, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/chegewara/.espressif/python_env/idf4.1_py2.7_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/home/chegewara/esp/esp-idf/requirements.txt']' returned non-zero exit status 1
```

**Comment by chegewara** [comment]
I fixed it by deleting old `~/.espressif` folder and run `install.sh` one more time. Also just in case i removed from `.profile` path to xtensa `PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin`.
