### ISSUE TITLE
undefined reference to mmgmt_enableRxbufOptFeature error after upgrade to idf v5.4.2

### ISSUE THREAD

**Issue by rxwen** [espressif/esp-idf#16375]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.4.2

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I'm building the [light](https://github.com/espressif/esp-matter/tree/release/v1.4/examples/light) example in esp-matter v1.4, for esp32c6 chip. It should be able to build and run.
Previously, I was using esp-idf v5.4.1, everything was fine.

### What is the actual behavior?

But after I upgrade to v5.4.2, also tried release/v5.4, release/v5.5 branch. The light sample will fail to build, the error was `undefined reference to mmgmt_enableRxbufOptFeature`. And the same v5.4.2 idf on ubuntu/linux is ok. 

### Steps to reproduce.

1. install esp-idf v5.4.2 on a macbook
2. clone the esp-matter repo, change to release/v1.4 branch
3. source esp-idf, and esp-matter export.sh files
4. cd to the esp-matter/examples/light
5. idf.py set-target esp32c6
6. idf.py build
...

### Build or installation Logs.

```plain

```

**Comment by zwx1995esp** [comment]
Hi @rxwen could you please share the full build logs? They might help us identify the issue more effectively

**Comment by rxwen** [comment]
`/Users/rxwen/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: esp-idf/bt/libbt.a(ble.c.obj): in function `ble_stack_enableVsCmds':
/Users/rxwen/projects/esp-idf-v5.4.2/components/bt/controller/esp32c6/ble.c:65:(.text.ble_stack_enableVsCmds+0x3e): undefined reference to `winWiden_stack_enableSetConstPeerScaVsCmd'
/Users/rxwen/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: esp-idf/bt/libbt.a(ble.c.obj): in function `ble_stack_enable':
/Users/rxwen/projects/esp-idf-v5.4.2/components/bt/controller/esp32c6/ble.c:145:(.text.ble_stack_enable+0x22): undefined reference to `mmgmt_enableRxbufOptFeature'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /Users/rxwen/projects/esp-matter/examples/light/build/log/idf_py_stderr_output_80817 and /Users/rxwen/projects/esp-matter/examples/light/build/log/idf_py_stdout_output_80817`

or refer to the attachment for full build log.

[build.log](https://github.com/user-attachments/files/21141502/build.log)
