### ISSUE TITLE
`AttributeError: module 'esptool' has no attribute '_main'` at idf5.+ (IDFGH-8149)

### ISSUE THREAD

**Issue by Coloryr** [espressif/esp-idf#9646]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

idf project can build with `idf5.0` on `vs code IDE`

### What is the actual behavior?

build fail with `idf5.0`, but use `idf4.4` can build successful

in idf4.4
![NW%$J@CU)}TN4{K4`E6863I](https://user-images.githubusercontent.com/26276037/186883127-5c809625-352b-4404-b129-6ccf7fc358b4.png)

in idf5.+(master)
![Y 0M3HE@$T$(H@}}%5G`L{H](https://user-images.githubusercontent.com/26276037/186884643-658c6295-d87d-4fde-b88e-9ed960abf550.png)

### Steps to reproduce.

1. install idf5.0
2. open project
3. run build command

**Comment by dobairoland** [comment]
Hi @Coloryr. Please take a look at hints posted [here](https://github.com/espressif/esp-idf/issues/9451#issuecomment-1198096270)

Duplicate of https://github.com/espressif/esp-idf/issues/9451

**Comment by dobairoland** [comment]
> build fail with idf5.0, but use idf4.4 can build successful

I think the setup of v4.4 is used with v5.0 (which is not compatible). Probably, you will have to re-run the setup so it would be re-generated for v5.0.

**Comment by Coloryr** [comment]
> > build fail with idf5.0, but use idf4.4 can build successful
> 
> I think the setup of v4.4 is used with v5.0 (which is not compatible). Probably, you will have to re-run the setup so it would be re-generated for v5.0.

my `esp-idf` uses `ESP-IDF VS Code Extension` to install

**Comment by Coloryr** [comment]
re-run `esp-idf\install.bat` can't fix

**Comment by dobairoland** [comment]
> All files have been deleted and reinstalled

What about `E:\workload\.espressif\python_env`?

**Comment by Coloryr** [comment]
> > All files have been deleted and reinstalled
> 
> What about `E:\workload\.espressif\python_env`?

Contains two folders:
![0U)V(IB2Z}C0C77J%H8PADD](https://user-images.githubusercontent.com/26276037/186887372-239d84ad-e6ba-439e-89a9-4119c0ca062c.png)

**Comment by Coloryr** [comment]
it may be a vs extension problem
idf5.+ can build successful with cmd
![N@3Z~3`@9V}T{DAM(V6_XIE](https://user-images.githubusercontent.com/26276037/186888241-ed51ae51-9836-49ef-b8db-5b4727c8abb7.png)

**Comment by dobairoland** [comment]
You could try to remove the 4.4 version. It could be one more in `E:\workload\.espressif\vscode\python_env` as well. That is why `export.bat` has no effect. If you still have an issue then please report it in https://github.com/espressif/vscode-esp-idf-extension. This relates to Vscode setup. You can get better help there.

**Comment by Coloryr** [comment]
> You could try to remove the 4.4 version. It could be one more in `E:\workload\.espressif\vscode\python_env` as well. That is why `export.bat` has no effect. If you still have an issue then please report it in https://github.com/espressif/vscode-esp-idf-extension. This relates to Vscode setup. You can get better help there.

thank you.
i will report to vscode extension.

**Comment by kurau1** [comment]
Hello, @Coloryr .
Do you solve the problem?
i am facing the same issue. i reinstall windows, reinstall VScode, it didn't work.
i wanna use idf5! it can bulid project successfully but can't flash device. and give this information in terminal.
```
Traceback (most recent call last):
  File "f:\ESP32\idf\esp-idf\components\esptool_py\esptool\esptool.py", line 22, in <module>
    esptool._main()  # type: ignore
AttributeError: module 'esptool' has no attribute '_main'
```
i have reinstall windows and vscode so many times. i install esp-idf v4.4 in VScode, it worked, can build and flash. but when i install esp-idf v5. i can't flash! it's a torture.

**Comment by Coloryr** [comment]
@kurau1 nope, but i have a better solution without use the vscode extension.

**Comment by kurau1** [comment]
> 

haha, me too, i edit program by vscode and flash by powershell, it can work T T
