### PR TITLE
fix(fatfs): re-enable FF_USE_EXPAND for contiguous file API (IDFGH-18287)

### LINKED ISSUE #19067: FF_USE_EXPAND set to 0 in v6.1, impacts esp_vfs_fat_create_contiguous_file (IDFGH-18260)
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v6.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Linker runs successfully, `esp_vfs_fat_create_contiguous_file` works

### What is the actual behavior?

Linker fails, `esp_vfs_fat_create_contiguous_file` can't find f_expand due to `ffconf.h` guard

### Steps to reproduce.

1. Call `esp_vfs_fat_create_contiguous_file` in your project via fatfs component
2. Try to build with esp-idf v6.1

### Build or installation Logs.

```plain
[... builds ok ...]

[...].espressif/tools/riscv32-esp-elf/esp-15.2.0_20251204/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/15.2.0/../../../../riscv32-esp-elf/bin/ld: esp-idf/fatfs/libfatfs.a(vfs_fat.c.obj): in function `esp_vfs_fat_create_contiguous_file':
[...].espressif/rolling/esp-idf/components/fatfs/vfs/vfs_fat.c:1528:(.text.esp_vfs_fat_create_contiguous_file+0xba): undefined reference to `f_expand'
```

### Diagnostic report archive.

_No response_

### More Information.

Set to 0 in current version, v6.1: https://github.com/espressif/esp-idf/blob/9bf0c0eb952fe4c075daf20e065ceb27a42ba8bf/components/fatfs/src/ffconf.h#L46

Set to 1 in previous version, v6.0: https://github.com/espressif/esp-idf/blob/16cd970a4342415c1d5856c3e064d05101a48cf3/components/fatfs/src/ffconf.h#L46

`f_expand` is used in `esp_vfs_fat_create_contiguous_file` here: https://github.com/espressif/esp-idf/blob/9bf0c0eb952fe4c075daf20e065ceb27a42ba8bf/components/fatfs/vfs/vfs_fat.c#L1538

Seems to have changed here: https://github.com/espressif/esp-idf/blame/9bf0c0eb952fe4c075daf20e065ceb27a42ba8bf/components/fatfs/src/ffconf.h#L46

### PR DESCRIPTION
**Pull request by andrewfree**
## Description

Fixes https://github.com/espressif/esp-idf/issues/19067 (IDFGH-18260).

`esp_vfs_fat_create_contiguous_file()` calls `f_expand()`, but `components/fatfs/src/ffconf.h` had `FF_USE_EXPAND` set to `0` on master (was `1` in v6.0), so linking against the public contiguous-file API failed with an undefined reference to `f_expand`.

This change restores `FF_USE_EXPAND` to `1` (matching other always-linked FatFs APIs in this file) and adds a Catch2 host regression that creates a contiguous file and verifies contiguity via `esp_vfs_fat_test_contiguous_file`.

## Testing

Host suite (`components/fatfs/host_test`) in Docker Ubuntu 24.04 aarch64:

- All tests passed (319 assertions in 16 test cases), including the new contiguous case (14 assertions)
- Mutation check: `FF_USE_EXPAND=0` → link fails with `undefined reference to f_expand` at `vfs_fat.c:1538`; restore → green

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by RathiSonika** [comment]
Hello, thank you for the PR. However, the issue has already been fixed, and the fix will be available in the GitHub ESP-IDF repository soon.

**Comment by RathiSonika** [comment]
Hello, fix is available in the commit 74a7a4b
So closing this PR
