### ISSUE TITLE
Mocking of IDF componnet does not work in 4.4.7 (IDFGH-12896)

### ISSUE THREAD

**Issue by yareach** [espressif/esp-idf#13857]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Previously I was using 3.3.3 where the unit tests and mocking worked. After moving to 4.4.7, the build does not work where the mocked components are. Here is a unit test with cJSON mock build log:
test/mocks/cJSON/mock_cJSON.c
test/mocks/cJSON/mock_cJSON.c:4834:7: error: conflicting types for 'cJSON_GetStringValue'
 char* cJSON_GetStringValue(cJSON* item)
In file included from 
test/mocks/cJSON/include/mock_cJSON.h:6,
                 from test/mocks/cJSON/mock_cJSON.c:6:
C:/Users/yarea_000/esp/esp-idf/components/json/cJSON/cJSON.h:179:22: note: previous declaration of 'cJSON_GetStringValue' was here
 CJSON_PUBLIC(char *) cJSON_GetStringValue(const cJSON * const item);

I used this line in the main cmake file:
set(TEST_EXCLUDE_COMPONENTS "ff" "esp_vfs_fat" "cJSON" "driver")
This line perfectly worked in 3.3.3 and it got built.

This is the cmake of the module which depends on cJSON:
file(TO_CMAKE_PATH "$ENV{CMOCK_PATH}" CMOCK_PATH)
set(COMPONENT_SRCDIRS   "."
                        "../../../test/mocks/filesystem"
                        "../../../test/mocks/cJSON"
                        ${CMOCK_PATH}/src
                        )
set(COMPONENT_ADD_INCLUDEDIRS   "../../../test/mocks/filesystem/include"
                                "../../../test/mocks/cJSON/include"
                                ${CMOCK_PATH}/src)

set(COMPONENT_REQUIRES unity jsoncomm)

register_component()

What changed in 4.4.7 that this does not work any longer?

**Comment by igrr** [comment]
Between IDF v3.3.3 and v4.4.7, cJSON library got updated from 1.7.12 to 1.7.17.

As the error message suggests, the function definition in your mock implementation file (test/mocks/cJSON/mock_cJSON.c) is not compatible with the declaration in cJSON header (esp-idf/components/json/cJSON/cJSON.h). I think this is because of this change in cJSON: https://github.com/DaveGamble/cJSON/commit/b95a4c56b05fb3200780c1cacc3b1659a2832f8e which first appeared in cJSON 1.7.14.
