### ISSUE TITLE
Build failed when not using ethernet (IDFGH-5269)

### ISSUE THREAD

**Issue by ataweg** [espressif/esp-idf#7034]
Update to the latest version results in a failed build.
```
C:/Espressif/esp-idf-master/components/esp_eth/src/esp_eth_mac_esp.c:58:21: error: 'CONFIG_ETH_DMA_RX_BUFFER_NUM' undeclared here (not in a function)
     uint8_t *rx_buf[CONFIG_ETH_DMA_RX_BUFFER_NUM];
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/esp-idf-master/components/esp_eth/src/esp_eth_mac_esp.c:59:21: error: 'CONFIG_ETH_DMA_TX_BUFFER_NUM' undeclared here (not in a function)
     uint8_t *tx_buf[CONFIG_ETH_DMA_TX_BUFFER_NUM];
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/esp-idf-master/components/esp_eth/src/esp_eth_mac_esp.c: In function 'esp_eth_mac_new_esp32':
C:/Espressif/esp-idf-master/components/esp_eth/src/esp_eth_mac_esp.c:449:47: error: 'CONFIG_ETH_DMA_BUFFER_SIZE' undeclared (first use in this function)
         emac->rx_buf[i] = heap_caps_calloc(1, CONFIG_ETH_DMA_BUFFER_SIZE, MALLOC_CAP_DMA);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Espressif/esp-idf-master/components/esp_eth/src/esp_eth_mac_esp.c:449:47: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [/c/Espressif/esp-idf-master/make/component_wrapper.mk:292: src/esp_eth_mac_esp.o] Error 1
make: *** [C:\Espressif\esp-idf-master/make/project.mk:642: component-esp_eth-build] Error 2

```
The problem was introduced with commit ef344d89ae961f21d1ebfa2f0eee8ef1f560a999. Because ...\components\ esp_eth\component.mk was not adjusted.
Please replace in that file
    `COMPONENT_OBJEXCLUDE += src/esp_eth_mac_esp32.o`
with
    `COMPONENT_OBJEXCLUDE += src/esp_eth_mac_esp.o`

Doing so the issue is gone.

**Comment by suda-morris** [comment]
Well spotted! We will fix it ASAP.
