### ISSUE TITLE
Dependency condition match breaks dependency linking (IDFGH-16628)

### ISSUE THREAD

**Issue by MiLeG** [espressif/esp-idf#17732]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.5.1

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

https://github.com/MiLeG/MRE-IDFGH-16628

The project has one direct dependency (MyComponent) in the project/components directory.
The main project component does not contain an idf_component manifest.

MyComponent declares an idf_component.yml manifest, as well as a KConfig.
The manifest defines a single conditional dependency (esp32-camera) which is included only when the MY_CAMERA config defined in the KConfig file is set to True.

Folder structure is like so:
Project
|-- components
|   |-- MyComponent
|       |-- src
|       |   |-- component.cpp
|       |-- CMakeLists.txt
|       |-- idf_component.yml
|       |-- KConfig.projbuild
|-- main
|   |-- CMakeLists.txt
|   |-- main.cpp
|-- CMakeLists.txt
|-- sdkconfig

I would expect that the esp32-camera dependency would be available to include in MyComponent/src/component.cpp

### What is the actual behavior?

Instead, the build fails since esp_camera.h isn't available in MyComponent/src/component.cpp.

However, the build succeeds when removing the dependency condition, so changing the MyComponent/idf_component.yml from:
```
dependencies:

  espressif/esp32-camera:
    version: "2.1.3"
    matches:
      - if: "$CONFIG{MY_CAMERA} == True"

  idf: '>=5.1.1'

```

to this:
```
dependencies:

  espressif/esp32-camera:
    version: "2.1.3"
#    matches:
#      - if: "$CONFIG{MY_CAMERA} == True"

  idf: '>=5.1.1'


```

### Steps to reproduce.

Running` idf.py flash` or similiar build command in the project root.

### Diagnostic report archive.

[idf-diag-47645f40-8bbf-4f86-9232-cbdcb917c0a8.zip](https://github.com/user-attachments/files/22908313/idf-diag-47645f40-8bbf-4f86-9232-cbdcb917c0a8.zip)

**Comment by igrr** [comment]
Shouldn't the include of esp_camera.h also be guarded by an `#ifdef CONFIG_MY_CAMERA`?

(Edit: sorry, I've missed the fact that you are reporting the issue for the case when CONFIG_MY_CAMERA=y.)

**Comment by MiLeG** [comment]
@igrr Yeah, the MRE was a bit hastily written.
Building with the config **turned on** was my focus here.

**Comment by SoucheSouche** [comment]
Hi @MiLeG, do you experience the issue when doing:
- `idf.py menuconfig`
- enable MY_CAMERA config
- `idf.py reconfigure`
- `idf.py build`

**Comment by MiLeG** [comment]
Following these steps the `idf.py build` command fails:
```
C:/Users/Emil/Documents/circuitmess/ESP-IDF-condDeps-MRE/components/MyComponent/src/component.cpp:1:10: fatal error: esp_camera.h: No such file or directory
    1 | #include <esp_camera.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

However, when writing the issue I seem to have glossed over this additional message in the output:
```
Compilation failed because component.cpp (in "MyComponent" component) includes esp_camera.h, provided by espressif__esp32-camera component(s).
However, espressif__esp32-camera component(s) is not in the requirements list of "MyComponent".
To fix this, add espressif__esp32-camera to PRIV_REQUIRES list of idf_component_register call in C:\Users\Emil\Documents\circuitmess\ESP-IDF-condDeps-MRE\components\MyComponent\CMakeLists.txt.
```

And yes, doing so does fix the issue!

My concern then is placing the component in the PRIV_REQUIRES or REQUIRES list seems bad practice since it's a conditional dependency controlled by the KConfig MY_CAMERA setting.
As referenced in the [docs](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#when-writing-a-component):
> The values of REQUIRES and PRIV_REQUIRES should not depend on any configuration options (CONFIG_xxx macros). This is because requirements are expanded before the configuration is loaded. Other component variables (like include paths or source files) can depend on configuration options.

Is there any way to work around this limitation?
I would really enjoy being able to include/remove conditional dependencies and use them in my component by just modifying a KConfig property.
Since the REQUIRES list in MyComponent/CMakeLists.txt idf_component_register() call shouldn't depend on a KConfig, I'm stuck achieving this.

**Comment by SoucheSouche** [comment]
ok, so I think that the value of `MY_CAMERA` has not been set yet when your dependency gets pulled in.

Maybe you could update you `idf_component.yml` to not contain the condition and move this condition in the `CMakeLists.txt`.

idf_component.yml
```
  espressif/esp32-camera:
    version: "2.1.3"

  idf: '>=5.1.1'
```

CMakeLists.txt
```
[...]

set(requires <components that will always be required>)
if (CONFIG_MY_CAMERA)
   list(APPEND requires esp32-camera)
endif()

idf_component_register(...
                       REQUIRES ${requires}
                       ...)

[...]
```

putting the component in REQUIRES or PRIV_REQUIRES is up to you but you get the idea.

Putting the condition in the CMakeLists.txt should make sure that the CONFIG_MY_CAMERA gets evaluated every time you update the Kconfig option by calling `idf.py menuconfig`.

**Comment by MiLeG** [comment]
Removing the condition in `idf_component.yml` defeats the point of using the IDF Component Manager.
The dependency will then get pulled (cloned or downloaded) even when it's not actually needed.

I would like to avoid this, and with a single KConfig make the dependency available to include while also removing or pulling it to the /managed_components directory.

**Comment by fhrbata** [comment]
Hello @MiLeG ,

the problem seems to be that v5.5.1 is missing 60e9ec429d87664822e3002dbb04b2efe2dd750f, specifically
```diff
diff --git a/tools/cmake/component.cmake b/tools/cmake/component.cmake
index 653533d3e9a5..37721f555508 100644
--- a/tools/cmake/component.cmake
+++ b/tools/cmake/component.cmake
@@ -243,6 +243,7 @@ function(__component_get_requirements)
             "idf_component_manager.prepare_components"
             "--project_dir=${project_dir}"
             "--lock_path=${DEPENDENCIES_LOCK}"
+            "--sdkconfig_json_file=${build_dir}/config/sdkconfig.json"
             "--interface_version=${component_manager_interface_version}"
             "inject_requirements"
             "--idf_path=${idf_path}"

```

Without this fix, the configuration is not passed to the component manager and it does not inject the `espressif__esp32-camera` dependency to `MyComponent`.  With this change it should IMHO work as you expect. No need to add dependencies into `CMakeLists.txt`.

**Comment by fhrbata** [comment]
This should be already fixed in `release/v5.5` branch with 5306cddaec0ecf8dfbd385b1a93415e42b17459f, so maybe you can give it a try to see if it solves your problem.

**Comment by MiLeG** [comment]
Yes, can confirm that with this commit/patch the conditional dependency include works as expected.

Closing the issue since it seems already fixed, just not in the latest release.

Hoping this commit makes it into v5.5.2 soon!
