### ISSUE TITLE
esp-idf-v4.3.1 dirent.h not C++ compatible ? (IDFGH-6173)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-idf#7850]
## Environment

- Development Kit:      Any esp32 
- Module or chip used:  ESP32
- IDF version (run ``git describe --tags`` to find it): 4.31
- Build System:         idf.py
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:  N/A

## Problem Description

Since upgrading from 4.3 to 4.3.1 of esp-idf, I get compile errors like below.
They disappear when including extern "C" { ... } around the #include <dirent.h> so I am guessing something is wrong with that file(s). There are multiple versions of it between the esp-idf and the compiler package mentioned above.

//Detailed problem description goes here.
[ 98%] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/ftpserv.cpp.obj
In file included from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.cpp:45:
/home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.h:42: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>: note: this is the location of the previous definition
In file included from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.h:55,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.cpp:45:
/home/danny/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/dirent.h:53:6: error: conflicting declaration of 'DIR* opendir(const char*)' with 'C' linkage
 DIR *opendir(const char *);
      ^~~~~~~
In file included from /home/danny/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/dirent.h:39,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.h:55,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.cpp:45:
/home/danny/src/github/esp32/esp-idf-v4.3.1/components/newlib/platform_include/sys/dirent.h:53:6: note: previous declaration with 'C++' linkage
 DIR* opendir(const char* name);
      ^~~~~~~
In file included from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.h:55,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.cpp:45:
/home/danny/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/dirent.h:56:3: error: conflicting declaration of 'dirent* readdir(DIR*)' with 'C' linkage
   readdir(DIR *);
   ^~~~~~~
In file included from /home/danny/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/dirent.h:39,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.h:55,
                 from /home/danny/src/esp-idf/espalarm-4.3/main/ftpserv.cpp:45:
/home/danny/src/github/esp32/esp-idf-v4.3.1/components/newlib/platform_include/sys/dirent.h:54:16: note: previous declaration with 'C++' linkage
 struct dirent* readdir(DIR* pdir);

**Comment by igrr** [comment]
Hi @dannybackx, this was reported in https://github.com/espressif/esp-idf/issues/7204 and fixed in https://github.com/espressif/esp-idf/commit/cbf207bfb83156ece449a10908cad0615d66ec52 on master and in https://github.com/espressif/esp-idf/commit/03109eb013c4603de2b074af9a43649ef74ee35b on release/v4.3.

**Comment by Alvin1Zhang** [comment]
@dannybackx Thanks for reporting, feel free to reopen.
