### ISSUE TITLE
Build error - "Wi-Fi Provisioning Manager Example" (IDFGH-14778)

### ISSUE THREAD

**Issue by ShanmugaCA** [espressif/esp-idf#15516]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.3.2

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

* ESP IDF example should build without any errors! But there is a build issue 

### What is the actual behavior?

1. run idf.py build 
2. Below errors observed.
3. Used the example code and no changes made other than setting the flash to 4 MB in menuconfig

+++++++++++++++++++++++++

/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c: In function 'app_main':

/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c:346:10: error: 'wifi_prov_mgr_config_t' has no member named 'wifi_prov_conn_cfg'
  346 |         .wifi_prov_conn_cfg = {
      |          ^~~~~~~~~~~~~~~~~~

/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c:347:13: error: 'wifi_prov_scheme_t' {aka 'struct wifi_prov_scheme'} has no member named 'wifi_conn_attempts'
  347 |            .wifi_conn_attempts =  CONFIG_EXAMPLE_PROV_MGR_CONNECTION_CNT,

+++++++++++++++++++++++++

### Steps to reproduce.

1. Step: Using Windows system, ESP IDF version 5.3.2 and idf.py for building from CMD prompt 
2. Step: download  .... git clone https://github.com/espressif/esp-idf.git
3. Step: In CMD prompt, change to the wifi provisionong manager ... cd esp-idf/examples/provisioning/wifi_prov_mgr
4. Step... idf.py menuconfig -> Serial Flash Config -> Flash size  -> 4MB ...set the 4MB flash 
5. Step ... run idf.py build ... getting the build error ... see the actual behaviour

### Build or installation Logs.

```plain
/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c: In function 'app_main':

/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c:346:10: error: 'wifi_prov_mgr_config_t' has no member named 'wifi_prov_conn_cfg'
  346 |         .wifi_prov_conn_cfg = {
      |          ^~~~~~~~~~~~~~~~~~


/esp-idf/examples/provisioning/wifi_prov_mgr/main/app_main.c:347:13: error: 'wifi_prov_scheme_t' {aka 'struct wifi_prov_scheme'} has no member named 'wifi_conn_attempts'
  347 |            .wifi_conn_attempts =  CONFIG_EXAMPLE_PROV_MGR_CONNECTION_CNT,
```

**Comment by ShanmugaCA** [comment]
Closed!

* The example code build without errors and worked in v5.3.2 after the addition of      wifi_prov_conn_cfg_t wifi_prov_conn_cfg;
inside the type wifi_prov_mgr_config_t;
 
* File name modified : manager.h

Tested and working as expected so closing this case!

Thanks,
BR,
Shanmuganathan

**Comment by ShanmugaCA** [comment]
Closed!

The example code build without errors and worked in v5.3.2 after the addition of wifi_prov_conn_cfg_t wifi_prov_conn_cfg;
inside the type wifi_prov_mgr_config_t;

File name modified : manager.h

Tested and working as expected so closing this case!

Thanks,
BR,
Shanmuganathan
