### ISSUE TITLE
Idf 4.3 cpu_start.c error (IDFGH-3717)

### ISSUE THREAD

**Issue by pilnikov** [espressif/esp-idf#5643]
After update from 4.2 to 4.3 i got the following error

`Z:/esp-idf/components/esp_system/port/cpu_start.c: In function 'call_start_cpu0':
Z:/esp-idf/components/esp_system/port/cpu_start.c:225:9: error: unknown type name 'wdt_hal_context_t'
         wdt_hal_context_t rtc_wdt_ctx = {.inst = WDT_RWDT, .rwdt_dev = &RTCCNTL};`

I fix it by add in cpu_start.c at line 54 

`#include "hal/wdt_hal.h"`

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we had a fix under internal reviewing. The issue will be closed automatically once the fix is available on GitHub. Thanks.

**Comment by pilnikov** [comment]
The new release was released - the error remained. Without adding #include "hal / wdt_hal.h" doesn't work
