### ISSUE TITLE
In V6.0.0: PERIPH_I2S1_MODULE disappeared from the components/soc/esp32/include/soc/periph_defs.h (IDFGH-17452)

### ISSUE THREAD

**Issue by turgu1** [espressif/esp-idf#18410]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v6.0

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Was well defined and working fine in v5.5.3.

### What is the actual behavior?

At compile time the following lines returned the following error: 

- error: 'PERIPH_I2S1_MODULE' was not declared in this scope

```
    periph_module_enable(PERIPH_I2S1_MODULE);
    periph_module_reset(PERIPH_I2S1_MODULE);
```

### Steps to reproduce.

1. Create a new empty project selecting ESP32 in VSCODE ESP-IDF extension
2. replace the main.c with the following code:
``` C
#include "esp_private/periph_ctrl.h"
#include "soc/i2s_reg.h"
#include "soc/i2s_struct.h"
#include "soc/periph_defs.h"

void app_main(void) { periph_module_enable(PERIPH_I2S1_MODULE); }
```
3. Press the ESP-IDF extension build button  to get it built.

### Build or installation Logs.

```plain
*  Executing task: ninja  

[1/9] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj 
/home/turgu1/.espressif/tools/xtensa-esp-elf/esp-15.2.0_20251204/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc -DESP_PLATFORM -DIDF_VER=\"v6.0\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/home/turgu1/Dev/test_i2s1/build/config -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_libc/platform_include -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/config/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/config/include/freertos -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/config/xtensa/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos -I/home/turgu1/.espressif/v6.0/esp-idf/components/freertos/esp_additions/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/include/soc -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/ldo/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/debug_probe/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/etm/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/mspi_timing_tuning/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/mspi_timing_tuning/tuning_scheme_impl/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/power_supply/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/modem/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/port/esp32/. -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hw_support/port/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/heap/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/heap/tlsf -I/home/turgu1/.espressif/v6.0/esp-idf/components/log/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/soc/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/soc/esp32 -I/home/turgu1/.espressif/v6.0/esp-idf/components/soc/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/soc/esp32/register -I/home/turgu1/.espressif/v6.0/esp-idf/components/hal/platform_port/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/hal/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/hal/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_rom/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_rom/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_rom/esp32/include/esp32 -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_rom/esp32 -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_common/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_system/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_system/port/soc -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_system/port/include/private -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_stdio/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/xtensa/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/xtensa/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/xtensa/deprecated_include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_gpio/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_gpio/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_usb/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_pmu/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_pmu/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_ana_conv/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_ana_conv/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_dma/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_i2s/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_i2s/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/spi_flash/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_mspi/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_mspi/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_gpspi/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_gpspi/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_clock/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_hal_clock/esp32/include -I/home/turgu1/.espressif/v6.0/esp-idf/components/esp_blockdev/include @"/home/turgu1/Dev/test_i2s1/build/toolchain/cflags" -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-error=extra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fno-shrink-wrap -fmacro-prefix-map=/home/turgu1/Dev/test_i2s1=. -fmacro-prefix-map=/home/turgu1/.espressif/v6.0/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu23 -Wno-old-style-declaration -fzero-init-padding-bits=all -fno-malloc-dce -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c /home/turgu1/Dev/test_i2s1/main/main.c
/home/turgu1/Dev/test_i2s1/main/main.c: In function 'app_main':
/home/turgu1/Dev/test_i2s1/main/main.c:6:44: error: 'PERIPH_I2S1_MODULE' undeclared (first use in this function); did you mean 'PERIPH_I2S0_MODULE'?
    6 | void app_main(void) { periph_module_enable(PERIPH_I2S1_MODULE); }
      |                                            ^~~~~~~~~~~~~~~~~~
      |                                            PERIPH_I2S0_MODULE
/home/turgu1/Dev/test_i2s1/main/main.c:6:44: note: each undeclared identifier is reported only once for each function it appears in
[2/9] Performing build step for 'bootloader'
[1/1] cd /home/turgu1/Dev/test_i2s1/build/bootloader && /home/turgu1/.espressif/tools/python/v6.0/venv/bin/python /home/turgu1/.espressif/v6.0/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/turgu1/Dev/test_i2s1/build/bootloader/bootloader.bin
Bootloader binary size 0x6610 bytes. 0x9f0 bytes (9%) free.
ninja: build stopped: subcommand failed.

 *  The terminal process "ninja" failed to launch (exit code: 1).
```

**Comment by suda-morris** [comment]
I'm sorry, this is a breaking change in esp-idf 6.0. Find the release note here: https://release-notes.espressif.tools/release/6.0

<img width="1575" height="134" alt="Image" src="https://github.com/user-attachments/assets/5f2ca497-8b19-4f37-af5f-f3a9d0ad02ae" />

The change is to facilitate the ESP32-P4 support and save more static memory. https://github.com/espressif/esp-idf/commit/f348a101f97d662cca2f42376314a767e4151aa7

So there's no central code to enable each module's register clock. Each peripheral module will provide its own low level functions to enable the clock. e.g. the I2S driver uses the following functions:

https://github.com/espressif/esp-idf/blob/44c77cbf46844cd056c923277ece745173cb270d/components/esp_driver_i2s/i2s_platform.c#L45-L47

**Comment by turgu1** [comment]
Thanks for the info. I will try that.

**Comment by wanckl** [comment]
@turgu1 Hi, Still any problem? Or close the issue, thanks
