### ISSUE TITLE
ESP-IDF 6 CMake - various issues (IDFGH-17902)

### ISSUE THREAD

**Issue by higaski** [espressif/esp-idf#18796]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v6.0.2

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### What is the expected behavior?

Just tried to switch to ESP-IDF 6 and it's giving me a hard time. I deliberately left the title vague because I fear that many more issues will arise here.  :weary:

1. My project (working fine with 5.5.4) now fails to compile. The very first error I get is
  ```sh
/home/vinci/esp/esp-idf/components/esp_libc/platform_include/stdio.h:17:2: error: '#include_next' is a GCC extension [-Werror=pedantic]
   17 | #include_next <stdio.h>
      |  ^~~~~~~~~~~~
  ```
  I don't force any flags on ESP-IDF, where does this come from? Does this mean that ESP-IDF now fails to compile by default?

2. `save-defconfig` is now completely broken for me. Inside my CMake file I use a function to determine the project version from git, something like this
  ```sh
version_from_git()
project(
    Firmware
    VERSION ${VERSION_FROM_GIT}
    LANGUAGES ASM C CXX)
  ```
  This used to work in 5.5.4. Now with 6.0.2 this function is no longer recognized, most likely due to all that CMake shenanigans you guys run without the users knowledge.

### What is the actual behavior?

.

### Steps to reproduce.

 .

### Build or installation Logs.

```plain

```

**Comment by Lapshin** [comment]
@higaski , it's impossible to understand what happened to your application and how you built it when there are no logs or reproduction steps

**Comment by higaski** [comment]
Here you go: https://github.com/higaski/IDFGH-17902

The first issue seems to be related to the library which gets included. This library sets warnings and errors based on the `PROJECT_IS_TOP_LEVEL` and `ESP_PLATFORM` variables  (Wpedantic among them). That `PROJECT_IS_TOP_LEVEL` does not work with ESP-IDF is a known issue. And with ESP-IDF 6 `ESP_PLATFORM` does not seem to be available any longer, so the workaround present in the library breaks as well.

```cmake
if(PROJECT_IS_TOP_LEVEL AND NOT ESP_PLATFORM)
  target_include_directories(ULF_COM INTERFACE include)
  target_common_warnings(ULF_COM INTERFACE)
  target_common_errors(ULF_COM INTERFACE)
else()
  target_include_directories(ULF_COM SYSTEM INTERFACE include)
endif()
```

**Comment by Lapshin** [comment]
@higaski , IDF v6.0 has changed compiler warnings handling ([link](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/migration-guides/release-6.x/6.0/build-system.html#compiler-options)):

I was able to build your sources after `CONFIG_COMPILER_DISABLE_DEFAULT_ERRORS=y` was added to sdkconfig.* files
Some warnings need to be addressed in ESP-IDF because it has not been tested with the pedantic option yet...

Regarding `ESP_PLATFORM` - it is still with us:
https://github.com/espressif/esp-idf/blob/v6.0.2/tools/cmake/build.cmake#L780-L781

**Comment by higaski** [comment]
Ok, thank you for checking. You were right!
The tag from that lib I'm checking out does not contain the check for `ESP_PLATFORM` and then sets `Wpedantic` on the INTERFACE target. I've updated the lib accordingly.

Any suggestions how to work around the `save-defconfig` issue?
```sh
 ╰─λ idf.py save-defconfig
CMake presets file found but no preset name given; using first preset: 'Debug'
Executing action: save-defconfig
Running cmake in directory /home/vinci/Develop/VSCode/IDFGH-17902/${sourceDir}/build
Executing "cmake -G Ninja -B /home/vinci/Develop/VSCode/IDFGH-17902/${sourceDir}/build -DPYTHON_DEPS_CHECKED=1 -DPYTHON=/home/vinci/.espressif/python_env/idf6.0_py3.14_env/bin/python -DESP_PLATFORM=1 -DCCACHE_ENABLE=False /home/vinci/Develop/VSCode/IDFGH-17902 --preset Debug"...
-- Found Git: /usr/bin/git (found version "2.55.0")
-- Component directory /home/vinci/esp/esp-idf/components/mqtt does not contain a CMakeLists.txt file. No component will be added
CMake Error at CMakeLists.txt:14 (version_from_git):
  Unknown CMake command "version_from_git".


-- Configuring incomplete, errors occurred!
cmake failed with exit code 1, output of the command is in the /home/vinci/Develop/VSCode/IDFGH-17902/${sourceDir}/build/log/idf_py_stderr_output_76015 and /home/vinci/Develop/VSCode/IDFGH-17902/${sourceDir}/build/log/idf_py_stdout_output_76015
```

/edit
Also strange, running `save-defconfig` creates a `${sourceDir}` folder in root

**Comment by Lapshin** [comment]
@fhrbata

**Comment by higaski** [comment]
That's odd
```
Running cmake in directory /home/vinci/Develop/VSCode/IDFGH-17902/${sourceDir}/build
```

No idea where this nesting comes from

/edit
Generally, all invocations of idf.py now fail for me.

/edit
What works is explicitly specifying the build folder, e.g.
```sh
idf.py -B build flash
```

**Comment by higaski** [comment]
idf.py issue here:
https://github.com/espressif/esp-idf/issues/18861

closing this
