### ISSUE TITLE
Can't build with `CONFIG_ESP_SYSTEM_HW_STACK_GUARD` because an old version of the `esp_hw_stack_guard_get_bounds()` API is being used by espcoredump (IDFGH-12547)

### ISSUE THREAD

**Issue by nomis** [espressif/esp-idf#13551]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3-dev-3225-g5a40bb8746

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Successful build

### What is the actual behavior?

```
22:32:03.771  /opt/esp/idf/components/espcoredump/src/core_dump_common.c: In function 'esp_core_dump_setup_stack':
22:32:03.771  /opt/esp/idf/components/espcoredump/src/core_dump_common.c:79:35: warning: passing argument 1 of 'esp_hw_stack_guard_get_bounds' makes integer from pointer without a cast [-Wint-conversion]
22:32:03.771     79 |     esp_hw_stack_guard_get_bounds(&s_stack_context.sp_min, &s_stack_context.sp_max);
22:32:03.771        |                                   ^~~~~~~~~~~~~~~~~~~~~~~
22:32:03.771        |                                   |
22:32:03.771        |                                   uint32_t * {aka long unsigned int *}
22:32:03.771  In file included from /opt/esp/idf/components/espcoredump/src/core_dump_common.c:16:
22:32:03.771  /opt/esp/idf/components/esp_system/port/include/private/esp_private/hw_stack_guard.h:25:45: note: expected 'uint32_t' {aka 'long unsigned int'} but argument is of type 'uint32_t *' {aka 'long unsigned int *'}
22:32:03.771     25 | void esp_hw_stack_guard_get_bounds(uint32_t core_id, uint32_t *sp_min, uint32_t *sp_max);
22:32:03.771        |                                    ~~~~~~~~~^~~~~~~
22:32:03.771  /opt/esp/idf/components/espcoredump/src/core_dump_common.c:79:5: error: too few arguments to function 'esp_hw_stack_guard_get_bounds'
22:32:03.771     79 |     esp_hw_stack_guard_get_bounds(&s_stack_context.sp_min, &s_stack_context.sp_max);
22:32:03.771        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22:32:03.771  /opt/esp/idf/components/esp_system/port/include/private/esp_private/hw_stack_guard.h:25:6: note: declared here
22:32:03.771     25 | void esp_hw_stack_guard_get_bounds(uint32_t core_id, uint32_t *sp_min, uint32_t *sp_max);
22:32:03.771        |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce.

Enable `CONFIG_ESP_SYSTEM_HW_STACK_GUARD` and build for the esp32c6

### More Information.

This was broken by 13b55386bf5c20bd906e79e0e7aee261f6afe0fc.

The function is declared in [components/esp_system/port/include/private/esp_private/hw_stack_guard.h](https://github.com/espressif/esp-idf/blob/5a40bb8746633477c07ff9a3e90016c37fa0dc0c/components/esp_system/port/include/private/esp_private/hw_stack_guard.h#L25):
```
void esp_hw_stack_guard_get_bounds(uint32_t core_id, uint32_t *sp_min, uint32_t *sp_max);
```

The old API is used in [components/espcoredump/src/core_dump_common.c](https://github.com/espressif/esp-idf/blob/5a40bb8746633477c07ff9a3e90016c37fa0dc0c/components/espcoredump/src/core_dump_common.c#L79):
```
#if CONFIG_ESP_SYSTEM_HW_STACK_GUARD
    /* Save the current area we are watching to restore it later */
    esp_hw_stack_guard_get_bounds(&s_stack_context.sp_min, &s_stack_context.sp_max);
    /* Since the stack is going to change, make sure we disable protection or an exception would be triggered */
    esp_hw_stack_guard_monitor_stop();
#endif // CONFIG_ESP_SYSTEM_HW_STACK_GUARD
```

It's used correctly in [components/esp_system/port/arch/riscv/panic_arch.c](https://github.com/espressif/esp-idf/blob/5a40bb8746633477c07ff9a3e90016c37fa0dc0c/components/esp_system/port/arch/riscv/panic_arch.c#L63):
```
esp_hw_stack_guard_get_bounds(core_id, &sp_min, &sp_max);
```

I recommend using a process that allows `if (CONFIG_ESP_SYSTEM_HW_STACK_GUARD) {` to be used instead of `#if CONFIG_ESP_SYSTEM_HW_STACK_GUARD` because the compiler will then always report compile failures and optimise it away if it's always false. (This is non-trivial with the current config system because `CONFIG_ESP_SYSTEM_HW_STACK_GUARD` is not `0` but undefined when unset.)

**Comment by erhankur** [comment]
@nomis Thanks for reporting. We will fix the build error and a test to catch the error earlier.
