### ISSUE TITLE
<format> missing 5.1.x (IDFGH-16711)

### ISSUE THREAD

**Issue by bryghtlabs-richard** [espressif/esp-idf#17800]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

broken in v5.1.6, works in 5.4.1, works in v6.0-dev-2980-gab149384e1

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

I expected to be able to include <format> in c++, so that I may use some existing code that depends on `std::format`

### What is the actual behavior?

I am unable to use standard C++20 code that uses `std::format`, due to the following error:

```
codec.cpp:2:10: fatal error: format: No such file or directory
    2 | #include <format>
      |          ^~~~~~~~
```

### Steps to reproduce.

1. build `esp-idf/examples/cxx/rtti` (should work)
2. add `#include <format>` to esp-idf/examples/cxx/rtti/main/rtti_example_main.cpp
3. rebuild -> fails

### Build or installation Logs.

```plain

```

### Diagnostic report archive.

didn't seem to work today

**Comment by KonstantinKondrashov** [comment]
Hi @bryghtlabs-richard!
v5.1.x ships with an older GCC/libstdc++ that does not provide C++20 <format> (i.e., std::format).
Please consider upgrading to ESP-IDF ≥ v5.4, where <format> is available.

**Comment by Bryght-Labs-Richard** [comment]
Thanks @KonstantinKondrashov , we're working on updating ESP-IDF as well.

https://docs.espressif.com/projects/esp-idf/en/v5.1.6/esp32/api-guides/cplusplus.html should probably be updated, it thinks C++23 is available, I didn't see anything explaining these restrictions.

**Comment by igrr** [comment]
Even when a certain GCC version generally supports the new version of the standard, a number of new features are often not yet implemented. I think we can link GCC's docs,

https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html
https://gcc.gnu.org/projects/cxx-status.html

from our C++ support page in the programming guide.

Edit: we already link that page! @bryghtlabs-richard do you find the existing link to GCC supported features page sufficient to answer this question?

**Comment by Bryght-Labs-Richard** [comment]
It might be nice to add to the Limitations section. I don't know if any intermediate versions are impacted, but 5.1.6 reaches end-of-support next month (I'm fine if it's better to just close this)
