### ISSUE TITLE
ssue with Setting Leader Weight and Router Downgrade Threshold in OpenThread

### ISSUE THREAD

**Issue by donaldkohcw** [espressif/esp-idf#15471]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 

I am currently working on an OpenThread using ESP-IDF v5.3.2 and I am trying to set the leader weight and router downgrade threshold in my OpenThread network. However, I am encountering some issues with the otOperationalDataset structure. Is following function supported in esp ot api?

    // Set the leader weight to 255
    otThreadSetLocalLeaderWeight(esp_openthread_get_instance(), 255);

    // Set the RouterDowngradeThreshold to 0
    otThreadSetRouterDowngradeThreshold(esp_openthread_get_instance(), 0);

I got following error:

C:/Espressif/frameworks/esp-idf-v5.3.2/examples/openthread/ot_cli_lead/main/esp_ot_cli.c:106:24: error: 'otOperationalDatasetComponents' has no member named 'mIsLeaderWeightPresent'
  106 |     dataset.mComponents.mIsLeaderWeightPresent = true;
      |                        ^
C:/Espressif/frameworks/esp-idf-v5.3.2/examples/openthread/ot_cli_lead/main/esp_ot_cli.c:107:12: error: 'otOperationalDataset' has no member named 'mLeaderWeight'
  107 |     dataset.mLeaderWeight = 255;
      |            ^
C:/Espressif/frameworks/esp-idf-v5.3.2/examples/openthread/ot_cli_lead/main/esp_ot_cli.c:110:24: error: 'otOperationalDatasetComponents' has no member named 'mIsRouterDowngradeThresholdPresent'
  110 |     dataset.mComponents.mIsRouterDowngradeThresholdPresent = true;
      |                        ^
C:/Espressif/frameworks/esp-idf-v5.3.2/examples/openthread/ot_cli_lead/main/esp_ot_cli.c:111:12: error: 'otOperationalDataset' has no member named 'mRouterDowngradeThreshold'
  111 |     dataset.mRouterDowngradeThreshold = 0;

Thanks,

**Comment by donaldkohcw** [comment]
Apart from that, I tried otCliInputLine("channel");, and it responded properly. However, when I used a command with a space, such as otCliInputLine("leaderweight 255");, the program hangs with the following error:

Guru Meditation Error: Core 0 panic'ed (Store access fault). Exception was unhandled.

Setting breakpoint at 0x42065622 and returning...
--- 0x42065622: ot::Utils::CmdLineParser::ParseCmd(char*, ot::Utils::CmdLineParser::Arg*, unsigned char) at C:/Espressif/frameworks/esp-idf-v5.3.2/components/openthread/openthread/src/core/utils/parse_cmdline.cpp:66
"
Thanks.
